# Use root/example as user/password credentials
version: '3.1'

services:
  # postgres:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   volumes:
  #     - pg-datavolume:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin123

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server --requirepass redisRum111
    restart: always

volumes:
  pg-datavolume:
